# Generated by Django 4.2.9 on 2024-07-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_etiqueta_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
