# Generated by Django 4.2.9 on 2024-08-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_devoluciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='informacion',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
