# Generated by Django 4.2.6 on 2024-07-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_devoluciones_alter_usuario_rol_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='etiqueta',
        ),
    ]
