# Generated by Django 4.2.6 on 2024-08-06 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_remove_producto_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosubcategoria',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto'),
        ),
        migrations.AlterField(
            model_name='productosubcategoria',
            name='id_sub_categoria_etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.subcategoriaetiqueta'),
        ),
        migrations.AlterField(
            model_name='subcategoriaetiqueta',
            name='id_categoria_etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoriaetiqueta'),
        ),
    ]
