# Generated by Django 4.2.6 on 2024-08-27 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_detalleventa_producto_alter_detalleventa_venta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='informacion',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Pagada'), (3, 'Rechazada')], default=1),
        ),
        migrations.CreateModel(
            name='ProductoTallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
                ('id_talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.tallas')),
            ],
        ),
    ]
