# Generated by Django 5.1.1 on 2024-09-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_carouselitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='imagen',
            field=models.ImageField(upload_to='carousel/'),
        ),
    ]
