# Generated by Django 5.1.1 on 2024-10-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_remove_devoluciones_usuario_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoluciones',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='devoluciones/'),
        ),
    ]
