# Generated by Django 5.1.1 on 2024-10-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pago',
            field=models.IntegerField(choices=[(1, 'Tarjeta de crédito'), (2, 'Tarjeta de débito'), (3, 'Efectivo')]),
        ),
    ]
