# Generated by Django 5.1.1 on 2024-10-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_comentarios_delete_comentario_alter_pedido_tipo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='nombre',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='comentarios',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
