# Generated by Django 5.1.1 on 2024-10-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_remove_comentarios_nombre_comentarios_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
